name = "hilltoppers-topping-bar"
main = "src/toppingBar.ts"
compatibility_date = "2026-09-17"
workers_dev = true

[[d1_databases]]
binding = "TOPPINGS_DB"
database_name = "hilltoppers-toppings"
database_id = "87cca241-ec36-40e1-a5a4-a69a6bd9c66f"

[vars]
FIREBASE_PROJECT_ID = "schedule-59d28"
TOPPING_EMAIL_DOMAINS = "student.stjacademy.org,stjacademy.org"
